### ISSUE TITLE
will not build with Node 8.1.x and NPM 5.6.x

### ISSUE THREAD

**Issue by mvberg** [barchart/marketdata-utilities-js#2]
```
C:\Users\mvber\git\marketdata-utilities-js (master) (@barchart/marketdata-utilities-js@3.0.1)
λ node -v
v8.1.2

C:\Users\mvber\git\marketdata-utilities-js (master) (@barchart/marketdata-utilities-js@3.0.1)
λ npm -v
5.6.0

C:\Users\mvber\git\marketdata-utilities-js (master) (@barchart/marketdata-utilities-js@3.0.1)
λ gulp
C:\Users\mvber\git\marketdata-utilities-js\node_modules\require-dir\index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (C:\Users\mvber\git\marketdata-utilities-js\node_modules\require-dir\index.js:93:37)
    at Object.<anonymous> (C:\Users\mvber\git\marketdata-utilities-js\node_modules\gulp-git\index.js:4:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\mvber\git\marketdata-utilities-js\gulpfile.js:7:11)

C:\Users\mvber\git\marketdata-utilities-js (master) (@barchart/marketdata-utilities-js@3.0.1)
```

related info here: https://github.com/tjunnone/npm-check-updates/issues/363

**Comment by bryaningl3** [comment]
3.0.2
